from __future__ import annotations

# Default registry entries for the data sources this tool realistically uses.
# Reliability is a working judgement (0-100), not an official rating.

DEFAULT_DATA_SOURCES: list[dict] = [
    {
        "name": "BORIS-D Bodenrichtwerte",
        "provider": "Gutachterausschuesse der Laender",
        "data_type": "ground_value",
        "license_type": "je Bundesland unterschiedlich (teils dl-de/by-2-0, teils kostenpflichtig)",
        "commercial_use_allowed": None,
        "attribution_required": True,
        "geographic_coverage": "Deutschland (je Land unterschiedlich aktuell)",
        "url": "https://www.bodenrichtwerte-boris.de",
        "update_frequency": "jaehrlich/zweijaehrlich je Land",
        "reliability_score": 85,
        "notes": "Amtliche Werte, aber Stichtagsbezogen. Fuer AfA-Kaufpreisaufteilung dokumentieren.",
    },
    {
        "name": "Kommunaler Mietspiegel",
        "provider": "Stadt / Gemeinde",
        "data_type": "rent_reference",
        "license_type": "oeffentlich, Stadt-spezifisch",
        "commercial_use_allowed": True,
        "attribution_required": True,
        "geographic_coverage": "nur Staedte mit (qualifiziertem) Mietspiegel",
        "update_frequency": "alle 2 Jahre",
        "reliability_score": 80,
        "notes": "Basis fuer Mietpreisbremse-Plausibilitaet. Manuell je Deal erfassen.",
    },
    {
        "name": "ImmoScout24 Suchagent",
        "provider": "ImmobilienScout24",
        "data_type": "listings",
        "license_type": "eigene Suchagenten-Mails (kein Scraping)",
        "commercial_use_allowed": None,
        "attribution_required": False,
        "geographic_coverage": "Deutschland",
        "update_frequency": "taeglich per E-Mail",
        "reliability_score": 70,
        "notes": "Angebotspreise, keine Transaktionspreise. Import ueber E-Mail-Parser.",
    },
    {
        "name": "Immowelt Suchagent",
        "provider": "Immowelt",
        "data_type": "listings",
        "license_type": "eigene Suchagenten-Mails (kein Scraping)",
        "commercial_use_allowed": None,
        "attribution_required": False,
        "geographic_coverage": "Deutschland",
        "update_frequency": "taeglich per E-Mail",
        "reliability_score": 65,
        "notes": "Zweitquelle zur Dedup-Kontrolle der Angebotslage.",
    },
    {
        "name": "Kleinanzeigen Suchagent",
        "provider": "Kleinanzeigen.de",
        "data_type": "listings",
        "license_type": "eigene Suchagenten-Mails (kein Scraping)",
        "commercial_use_allowed": None,
        "attribution_required": False,
        "geographic_coverage": "Deutschland",
        "update_frequency": "taeglich per E-Mail",
        "reliability_score": 45,
        "notes": "Viele Privatverkaeufer und Off-Market-Naehe, aber unstrukturierte Daten.",
    },
    {
        "name": "ZVG-Portal Zwangsversteigerungen",
        "provider": "Justizportale der Laender",
        "data_type": "foreclosures",
        "license_type": "oeffentlich",
        "commercial_use_allowed": True,
        "attribution_required": False,
        "geographic_coverage": "Deutschland",
        "url": "https://www.zvg-portal.de",
        "update_frequency": "laufend",
        "reliability_score": 75,
        "notes": "Verkehrswertgutachten oft beigefuegt - wertvolle Vergleichsdaten.",
    },
    {
        "name": "Zensus 2022",
        "provider": "Statistische Aemter",
        "data_type": "demographics",
        "license_type": "dl-de/by-2-0",
        "commercial_use_allowed": True,
        "attribution_required": True,
        "geographic_coverage": "Deutschland (Gitterzellen/Gemeinden)",
        "url": "https://www.zensus2022.de",
        "update_frequency": "statisch (Stichtag 15.05.2022)",
        "reliability_score": 90,
        "notes": "Leerstandsquoten und Demografie fuer Lagebewertung.",
    },
    {
        "name": "Manuelle Erfassung (Expose/Makler/Verwalter)",
        "provider": "eigene Recherche",
        "data_type": "manual",
        "license_type": "eigene Daten",
        "commercial_use_allowed": True,
        "attribution_required": False,
        "geographic_coverage": "je Deal",
        "update_frequency": "je Deal",
        "reliability_score": 60,
        "notes": "Qualitaet haengt von der Quelle ab - immer mit Datum dokumentieren.",
    },
]
