from __future__ import annotations

from typing import Optional

from app.services.scoring import LocationMetricsInput


class LocationEnrichmentService:
    def enrich(self, city: Optional[str], postal_code: Optional[str]) -> LocationMetricsInput:
        raise NotImplementedError


class MockLocationEnrichmentService(LocationEnrichmentService):
    """Placeholder for future licensed/open-data location enrichment."""

    city_profiles = {
        "Leipzig": LocationMetricsInput(
            population_trend_score=82,
            vacancy_risk_score=74,
            purchasing_power_score=67,
            public_transport_score=80,
            employer_access_score=75,
            micro_location_score=78,
            transit_access_score=82,
            daily_needs_score=80,
            demand_anchor_score=77,
            leisure_quality_score=74,
            short_term_rental_score=63,
            nuisance_resilience_score=68,
            noise_risk_score=68,
            flood_risk_score=72,
            climate_resilience_score=70,
        ),
        "Dresden": LocationMetricsInput(
            population_trend_score=76,
            vacancy_risk_score=72,
            purchasing_power_score=72,
            public_transport_score=78,
            employer_access_score=76,
            micro_location_score=74,
            transit_access_score=79,
            daily_needs_score=76,
            demand_anchor_score=78,
            leisure_quality_score=82,
            short_term_rental_score=66,
            nuisance_resilience_score=71,
            noise_risk_score=70,
            flood_risk_score=76,
            climate_resilience_score=72,
        ),
        "Dortmund": LocationMetricsInput(
            population_trend_score=63,
            vacancy_risk_score=64,
            purchasing_power_score=61,
            public_transport_score=70,
            employer_access_score=68,
            micro_location_score=62,
            transit_access_score=71,
            daily_needs_score=66,
            demand_anchor_score=70,
            leisure_quality_score=61,
            short_term_rental_score=47,
            nuisance_resilience_score=58,
            noise_risk_score=58,
            flood_risk_score=70,
            climate_resilience_score=63,
        ),
        "Berlin": LocationMetricsInput(
            population_trend_score=88,
            vacancy_risk_score=86,
            purchasing_power_score=78,
            public_transport_score=92,
            employer_access_score=90,
            micro_location_score=84,
            transit_access_score=94,
            daily_needs_score=88,
            demand_anchor_score=92,
            leisure_quality_score=82,
            short_term_rental_score=72,
            nuisance_resilience_score=55,
            noise_risk_score=54,
            flood_risk_score=75,
            climate_resilience_score=58,
        ),
        "Hamburg": LocationMetricsInput(
            population_trend_score=82,
            vacancy_risk_score=80,
            purchasing_power_score=82,
            public_transport_score=86,
            employer_access_score=84,
            micro_location_score=78,
            transit_access_score=87,
            daily_needs_score=84,
            demand_anchor_score=86,
            leisure_quality_score=80,
            short_term_rental_score=70,
            nuisance_resilience_score=59,
            noise_risk_score=58,
            flood_risk_score=62,
            climate_resilience_score=62,
        ),
        "Munich": LocationMetricsInput(
            population_trend_score=86,
            vacancy_risk_score=88,
            purchasing_power_score=92,
            public_transport_score=90,
            employer_access_score=92,
            micro_location_score=86,
            transit_access_score=92,
            daily_needs_score=89,
            demand_anchor_score=94,
            leisure_quality_score=84,
            short_term_rental_score=73,
            nuisance_resilience_score=64,
            noise_risk_score=62,
            flood_risk_score=78,
            climate_resilience_score=57,
        ),
        "Essen": LocationMetricsInput(
            population_trend_score=58,
            vacancy_risk_score=61,
            purchasing_power_score=59,
            public_transport_score=68,
            employer_access_score=66,
            micro_location_score=56,
            transit_access_score=69,
            daily_needs_score=63,
            demand_anchor_score=65,
            leisure_quality_score=58,
            short_term_rental_score=43,
            nuisance_resilience_score=57,
            noise_risk_score=60,
            flood_risk_score=68,
            climate_resilience_score=64,
        ),
        "Hannover": LocationMetricsInput(
            population_trend_score=67,
            vacancy_risk_score=68,
            purchasing_power_score=69,
            public_transport_score=78,
            employer_access_score=73,
            micro_location_score=69,
            transit_access_score=79,
            daily_needs_score=72,
            demand_anchor_score=75,
            leisure_quality_score=70,
            short_term_rental_score=58,
            nuisance_resilience_score=64,
            noise_risk_score=64,
            flood_risk_score=72,
            climate_resilience_score=68,
        ),
    }

    def enrich(self, city: Optional[str], postal_code: Optional[str]) -> LocationMetricsInput:
        if city in self.city_profiles:
            return self.city_profiles[city]
        return LocationMetricsInput()
