from __future__ import annotations

from decimal import Decimal


DEMO_LISTINGS = [
    {
        "source": "demo_seed",
        "external_id": "demo-strong-leipzig",
        "title": "Synthetic strong deal - Leipzig Altbau unit",
        "description": "Fictional apartment case with solid yield, acceptable energy data, and complete WEG assumptions.",
        "street": "Beispielstrasse",
        "house_number": "11",
        "city": "Leipzig",
        "postal_code": "04129",
        "federal_state": "Sachsen",
        "purchase_price": Decimal("165000"),
        "living_area_sqm": Decimal("58"),
        "number_of_rooms": Decimal("2"),
        "floor": "2",
        "construction_year": 1998,
        "condition": "gepflegt",
        "energy_class": "C",
        "heating_type": "Fernwaerme",
        "energy_consumption_kwh": Decimal("92"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("925"),
        "market_rent_estimate_monthly": Decimal("960"),
        "house_money_monthly": Decimal("210"),
        "non_recoverable_costs_monthly": Decimal("70"),
        "maintenance_reserve_weg": Decimal("360000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("5.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("4000"),
        "listing_url": "https://example.invalid/demo-strong-leipzig",
    },
    {
        "source": "demo_seed",
        "external_id": "demo-overpriced-berlin",
        "title": "Synthetic overpriced deal - Berlin compact unit",
        "description": "Fictional apartment priced materially above model fair value.",
        "street": "Musterweg",
        "house_number": "7",
        "city": "Berlin",
        "postal_code": "10405",
        "federal_state": "Berlin",
        "purchase_price": Decimal("415000"),
        "living_area_sqm": Decimal("49"),
        "number_of_rooms": Decimal("2"),
        "floor": "4",
        "construction_year": 2010,
        "condition": "gut",
        "energy_class": "B",
        "heating_type": "Gas",
        "energy_consumption_kwh": Decimal("78"),
        "is_rented": False,
        "cold_rent_monthly": Decimal("1170"),
        "market_rent_estimate_monthly": Decimal("1250"),
        "house_money_monthly": Decimal("240"),
        "non_recoverable_costs_monthly": Decimal("90"),
        "maintenance_reserve_weg": Decimal("240000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("6"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("5000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-negative-cashflow-hamburg",
        "title": "Synthetic negative cashflow deal - Hamburg",
        "description": "Fictional case with high price and financing burden.",
        "street": "Kapitalring",
        "house_number": "3",
        "city": "Hamburg",
        "postal_code": "22083",
        "federal_state": "Hamburg",
        "purchase_price": Decimal("355000"),
        "living_area_sqm": Decimal("55"),
        "number_of_rooms": Decimal("2"),
        "floor": "1",
        "construction_year": 1978,
        "condition": "renovierungsbeduerftig",
        "energy_class": "E",
        "heating_type": "Oel",
        "energy_consumption_kwh": Decimal("146"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("850"),
        "market_rent_estimate_monthly": Decimal("980"),
        "house_money_monthly": Decimal("310"),
        "non_recoverable_costs_monthly": Decimal("145"),
        "maintenance_reserve_weg": Decimal("120000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("5.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("18000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-missing-weg-dortmund",
        "title": "Synthetic missing WEG data - Dortmund",
        "description": "Fictional case missing maintenance reserve and document clarity.",
        "street": "Pruefallee",
        "house_number": "21",
        "city": "Dortmund",
        "postal_code": "44139",
        "federal_state": "NRW",
        "purchase_price": Decimal("145000"),
        "living_area_sqm": Decimal("52"),
        "number_of_rooms": Decimal("2"),
        "floor": "3",
        "construction_year": 1969,
        "condition": "teilmodernisiert",
        "energy_class": "D",
        "heating_type": "Gas",
        "energy_consumption_kwh": Decimal("122"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("610"),
        "market_rent_estimate_monthly": Decimal("690"),
        "house_money_monthly": Decimal("255"),
        "non_recoverable_costs_monthly": Decimal("95"),
        "maintenance_reserve_weg": None,
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("6.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("9000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-poor-energy-essen",
        "title": "Synthetic poor energy class deal - Essen",
        "description": "Fictional case with H energy class and insufficient capex buffer.",
        "street": "Heizungsweg",
        "house_number": "5",
        "city": "Essen",
        "postal_code": "45127",
        "federal_state": "NRW",
        "purchase_price": Decimal("132000"),
        "living_area_sqm": Decimal("47"),
        "number_of_rooms": Decimal("2"),
        "floor": "EG",
        "construction_year": 1958,
        "condition": "einfach",
        "energy_class": "H",
        "heating_type": "Gas",
        "energy_consumption_kwh": Decimal("248"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("575"),
        "market_rent_estimate_monthly": Decimal("620"),
        "house_money_monthly": Decimal("210"),
        "non_recoverable_costs_monthly": Decimal("88"),
        "maintenance_reserve_weg": Decimal("42000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("6.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("3000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-below-market-dresden",
        "title": "Synthetic rented below market deal - Dresden",
        "description": "Fictional case where current rent is below market and rent law must be checked.",
        "street": "Mietspiegelplatz",
        "house_number": "14",
        "city": "Dresden",
        "postal_code": "01127",
        "federal_state": "Sachsen",
        "purchase_price": Decimal("168000"),
        "living_area_sqm": Decimal("61"),
        "number_of_rooms": Decimal("3"),
        "floor": "2",
        "construction_year": 1994,
        "condition": "gut",
        "energy_class": "C",
        "heating_type": "Fernwaerme",
        "energy_consumption_kwh": Decimal("101"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("560"),
        "market_rent_estimate_monthly": Decimal("760"),
        "house_money_monthly": Decimal("235"),
        "non_recoverable_costs_monthly": Decimal("82"),
        "maintenance_reserve_weg": Decimal("210000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("3.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("7000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-high-house-money-hannover",
        "title": "Synthetic high house money deal - Hannover",
        "description": "Fictional case with unusually high WEG monthly burden.",
        "street": "Kostenstrasse",
        "house_number": "9",
        "city": "Hannover",
        "postal_code": "30161",
        "federal_state": "Niedersachsen",
        "purchase_price": Decimal("198000"),
        "living_area_sqm": Decimal("64"),
        "number_of_rooms": Decimal("3"),
        "floor": "5",
        "construction_year": 1982,
        "condition": "mittel",
        "energy_class": "E",
        "heating_type": "Gas",
        "energy_consumption_kwh": Decimal("158"),
        "is_rented": True,
        "cold_rent_monthly": Decimal("780"),
        "market_rent_estimate_monthly": Decimal("830"),
        "house_money_monthly": Decimal("520"),
        "non_recoverable_costs_monthly": Decimal("245"),
        "maintenance_reserve_weg": Decimal("90000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("12000"),
    },
    {
        "source": "demo_seed",
        "external_id": "demo-good-location-low-yield-munich",
        "title": "Synthetic good location but low yield - Munich",
        "description": "Fictional premium location case with low initial yield.",
        "street": "Lageblick",
        "house_number": "18",
        "city": "Munich",
        "postal_code": "80796",
        "federal_state": "Bayern",
        "purchase_price": Decimal("515000"),
        "living_area_sqm": Decimal("53"),
        "number_of_rooms": Decimal("2"),
        "floor": "3",
        "construction_year": 2016,
        "condition": "sehr gut",
        "energy_class": "A",
        "heating_type": "Fernwaerme",
        "energy_consumption_kwh": Decimal("48"),
        "is_rented": False,
        "cold_rent_monthly": Decimal("1325"),
        "market_rent_estimate_monthly": Decimal("1420"),
        "house_money_monthly": Decimal("260"),
        "non_recoverable_costs_monthly": Decimal("95"),
        "maintenance_reserve_weg": Decimal("510000"),
        "broker_fee_percent": Decimal("3.57"),
        "property_transfer_tax_percent": Decimal("3.5"),
        "notary_and_land_registry_percent": Decimal("2"),
        "expected_initial_capex": Decimal("3000"),
    },
]
